version: "3.8"

services:
  forum:
    build: .
    container_name: forum_app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - forum_data:/app/data
      - static_data:/app/static  # Mount the static directory for image uploads
    environment:
      - DATABASE_URL=/app/data/forum.db

volumes:
  forum_data:
  static_data:  # Define the volume for static files
